version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "microcms"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fd0wbwoq4rjc"
s3_prefix = "microcms"
region = "eu-west-3"
profile = "perso"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
